name: pr_test_code
on:
  push:
      branches: [main] 
  pull_request:
      branches: [main] 
jobs:
  python-hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"
      - run: python test.py
      - run: python test1.py
